create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  transaction_date date not null,
  amount numeric(12, 2) not null check (amount >= 0),
  category text not null check (char_length(category) > 0),
  created_at timestamptz not null default now(),
  unique (transaction_date, amount, category)
);

alter table public.transactions enable row level security;

drop policy if exists "Transactions are publicly readable" on public.transactions;

create policy "Transactions are publicly readable"
on public.transactions
for select
to anon, authenticated
using (true);

delete from public.transactions;

insert into public.transactions (transaction_date, amount, category)
values
  ('2026-08-11', 1118.40, 'Groceries'),
  ('2026-08-09', 43.00, 'Transportation'),
  ('2026-08-07', 89.99, 'Shopping'),
  ('2026-08-05', 24.50, 'Dining'),
  ('2026-08-02', 1250.00, 'Housing')
on conflict (transaction_date, amount, category) do nothing;
