create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  name_zh text not null check (char_length(trim(name_zh)) between 1 and 60),
  name_en text not null check (char_length(trim(name_en)) between 1 and 60),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (parent_id is null or parent_id <> id)
);
create index if not exists categories_parent_id_idx on public.categories(parent_id);
create index if not exists categories_user_id_idx on public.categories(user_id);
alter table public.categories enable row level security;
create policy "Users can view common and own categories" on public.categories for select to authenticated using (user_id is null or user_id = (select auth.uid()));
create policy "Users can create own categories" on public.categories for insert to authenticated with check (user_id = (select auth.uid()));
create policy "Users can update own categories" on public.categories for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "Users can delete own categories" on public.categories for delete to authenticated using (user_id = (select auth.uid()));

create or replace function public.validate_category_parent() returns trigger language plpgsql set search_path = public as $$
declare parent_user_id uuid; declare parent_parent_id bigint;
begin
  if new.parent_id is null then return new; end if;
  select user_id, parent_id into parent_user_id, parent_parent_id from public.categories where id = new.parent_id;
  if not found then raise exception 'Parent category does not exist'; end if;
  if parent_parent_id is not null then raise exception 'Categories support only two levels'; end if;
  if parent_user_id is distinct from new.user_id then raise exception 'A category and its parent must have the same owner'; end if;
  return new;
end; $$;
drop trigger if exists validate_category_parent_trigger on public.categories;
create trigger validate_category_parent_trigger before insert or update of parent_id, user_id on public.categories for each row execute function public.validate_category_parent();

create or replace function public.admin_list_categories(session_token_hash text) returns setof public.categories language plpgsql security definer set search_path = public as $$
begin
  if public.verify_admin_session(session_token_hash) is null then raise exception 'unauthorized'; end if;
  return query select * from public.categories where user_id is null order by created_at asc, id asc;
end; $$;
create or replace function public.admin_create_category(session_token_hash text, category_name_zh text, category_name_en text, category_parent_id bigint default null)
returns bigint language plpgsql security definer set search_path = public as $$
declare new_id bigint;
begin
  if public.verify_admin_session(session_token_hash) is null then raise exception 'unauthorized'; end if;
  if trim(category_name_zh) = '' or trim(category_name_en) = '' then raise exception 'Chinese and English names are required'; end if;
  insert into public.categories(parent_id, user_id, name_zh, name_en) values (category_parent_id, null, trim(category_name_zh), trim(category_name_en)) returning id into new_id;
  return new_id;
end; $$;
revoke all on public.categories from anon;
grant select, insert, update, delete on public.categories to authenticated;
grant usage, select on sequence public.categories_id_seq to authenticated;
grant execute on function public.admin_list_categories(text), public.admin_create_category(text,text,text,bigint) to anon, authenticated;
