create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists customers_user_id_idx on public.customers(user_id);

alter table public.customers enable row level security;

create policy "Users can view own customers" on public.customers for select to authenticated
using (user_id = (select auth.uid()));
create policy "Users can create own customers" on public.customers for insert to authenticated
with check (user_id = (select auth.uid()));
create policy "Users can update own customers" on public.customers for update to authenticated
using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "Users can delete own customers" on public.customers for delete to authenticated
using (user_id = (select auth.uid()));

revoke all on public.customers from anon;
grant select, insert, update, delete on public.customers to authenticated;
grant usage, select on sequence public.customers_id_seq to authenticated;
