create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  content text not null check (char_length(content) between 1 and 5000),
  thumbnail bytea not null check (octet_length(thumbnail) between 1 and 2097152),
  thumbnail_mime text not null check (thumbnail_mime in ('image/jpeg', 'image/png', 'image/webp', 'image/gif')),
  created_at timestamptz not null default now()
);

alter table public.notices enable row level security;
revoke all on public.notices from anon, authenticated;

create or replace function public.admin_list_notices(session_token_hash text)
returns table (id bigint, title text, content text, thumbnail_data text, thumbnail_mime text, created_at timestamptz)
language plpgsql security definer set search_path = public as $$
begin
  if public.verify_admin_session(session_token_hash) is null then raise exception 'unauthorized'; end if;
  return query
    select n.id, n.title, n.content, encode(n.thumbnail, 'base64'), n.thumbnail_mime, n.created_at
    from public.notices n
    order by n.created_at desc, n.id desc;
end;
$$;

create or replace function public.admin_create_notice(
  session_token_hash text,
  notice_title text,
  notice_content text,
  thumbnail_base64 text,
  thumbnail_content_type text
)
returns bigint language plpgsql security definer set search_path = public as $$
declare
  notice_id bigint;
  thumbnail_bytes bytea;
begin
  if public.verify_admin_session(session_token_hash) is null then raise exception 'unauthorized'; end if;
  if thumbnail_content_type not in ('image/jpeg', 'image/png', 'image/webp', 'image/gif') then raise exception 'invalid image type'; end if;
  thumbnail_bytes := decode(thumbnail_base64, 'base64');
  if octet_length(thumbnail_bytes) < 1 or octet_length(thumbnail_bytes) > 2097152 then raise exception 'invalid image size'; end if;

  insert into public.notices (title, content, thumbnail, thumbnail_mime)
  values (trim(notice_title), trim(notice_content), thumbnail_bytes, thumbnail_content_type)
  returning id into notice_id;
  return notice_id;
end;
$$;

grant execute on function public.admin_list_notices(text), public.admin_create_notice(text,text,text,text,text) to anon, authenticated;
