create extension if not exists pgcrypto with schema extensions;

create table if not exists public.admin_accounts (
  id bigint generated by default as identity primary key,
  username text not null unique check (char_length(username) between 3 and 50),
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_sessions (
  id bigint generated by default as identity primary key,
  admin_id bigint not null references public.admin_accounts(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

alter table public.admin_accounts enable row level security;
alter table public.admin_sessions enable row level security;

insert into public.admin_accounts (username, password_hash)
values ('Wangyu', extensions.crypt('753951', extensions.gen_salt('bf', 12)))
on conflict (username) do update set password_hash = excluded.password_hash;

create or replace function public.verify_admin_session(session_token_hash text)
returns text language plpgsql security definer set search_path = public, extensions as $$
declare result text;
begin
  select a.username into result from public.admin_sessions s join public.admin_accounts a on a.id = s.admin_id
  where s.token_hash = session_token_hash and s.expires_at > now();
  return result;
end; $$;

create or replace function public.authenticate_admin(login_username text, login_password text, new_token_hash text)
returns boolean language plpgsql security definer set search_path = public, extensions as $$
declare account_id bigint;
begin
  select id into account_id from public.admin_accounts where username = login_username and password_hash = extensions.crypt(login_password, password_hash);
  if account_id is null then return false; end if;
  delete from public.admin_sessions where expires_at <= now();
  insert into public.admin_sessions(admin_id, token_hash, expires_at) values (account_id, new_token_hash, now() + interval '8 hours');
  return true;
end; $$;

create or replace function public.revoke_admin_session(session_token_hash text)
returns void language sql security definer set search_path = public as $$ delete from public.admin_sessions where token_hash = session_token_hash; $$;

create or replace function public.admin_list_transactions(session_token_hash text)
returns setof public.transactions language plpgsql security definer set search_path = public as $$
begin
  if public.verify_admin_session(session_token_hash) is null then raise exception 'unauthorized'; end if;
  return query select * from public.transactions order by transaction_date desc;
end; $$;

create or replace function public.admin_create_transaction(session_token_hash text, transaction_date date, amount numeric, category text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if public.verify_admin_session(session_token_hash) is null then raise exception 'unauthorized'; end if;
  insert into public.transactions(transaction_date, amount, category) values (transaction_date, amount, category);
end; $$;

create or replace function public.admin_update_transaction(session_token_hash text, transaction_id bigint, transaction_date date, amount numeric, category text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if public.verify_admin_session(session_token_hash) is null then raise exception 'unauthorized'; end if;
  update public.transactions set transaction_date = admin_update_transaction.transaction_date, amount = admin_update_transaction.amount, category = admin_update_transaction.category where id = transaction_id;
end; $$;

create or replace function public.admin_delete_transaction(session_token_hash text, transaction_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  if public.verify_admin_session(session_token_hash) is null then raise exception 'unauthorized'; end if;
  delete from public.transactions where id = transaction_id;
end; $$;

revoke all on public.admin_accounts, public.admin_sessions from anon, authenticated;
grant execute on function public.verify_admin_session(text), public.authenticate_admin(text,text,text), public.revoke_admin_session(text), public.admin_list_transactions(text), public.admin_create_transaction(text,date,numeric,text), public.admin_update_transaction(text,bigint,date,numeric,text), public.admin_delete_transaction(text,bigint) to anon, authenticated;
